/*
 * @LastEditors: John
 * @Date: 2024-01-07 17:41:03
 * @LastEditTime: 2024-01-07 19:20:34
 * @Author: John
 */
/* This file was initially auto-generated by https://github.com/pmndrs/gltfjsx and then adapted manually */

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";
import { useEffect } from "react";

export default function Shoe({ ...props }: any) {
  // const { nodes, materials } = useGLTF("/shoe.gltf");

  const { nodes: roos_nodes, materials: roos_materials } = useGLTF("/roos.glb");

  useEffect(() => {
    console.log("roos:", roos_nodes, roos_materials);
  }, [roos_nodes, roos_materials]);

  // useEffect(() => {
  //   console.log("shoe:", nodes, materials);
  // }, [nodes, materials]);
  // The following is a read-out of the models contents, all of its
  // meshes, groups and so on.
  return (
    <group {...props} dispose={null}>
      {/* We can alter materials by piercing into them: materia-property={...} */}
      <mesh
        castShadow
        receiveShadow
        geometry={roos_nodes["立方体"].geometry}
        material={roos_materials["材质"]}
      />
    </group>
  );
}
